---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mvilliger/dynatrace-cli
    tag: "latest"

inputs:
- name: PivotalDevOpsTutorial
#- name: current-app-info

run:
  path: /bin/sh ./PivotalDevOpsTutorial/ci/tasks/init-dynatrace-task