---
applications:
- name: APPNAME
  memory: 256M
  instances: 1
  command: node app.js
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
  env:
#    DT_CLUSTER_ID: devops-sample-app-prod
    DT_NODE_ID: APPNAME
    DT_CUSTOM_PROP: DEPLOYMENT_GRP_NAME=Production DEPLOYMENT_COLOR=APPCOLOR
    BUILD_NUMBER: 1

