---
applications:
- name: devops-sample-app
  memory: 256M
  instances: 1
#  host: devops-sample-app
  command: node app.js
  path: .
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack.git
  env:
    DT_CUSTOM_PROP: DEPLOYMENT_GROUP=Staging
    BUILD_NUMBER: 4

